# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Calculadora.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QHeaderView,
    QLabel, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(723, 684)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 20, 671, 571))
        self.frame.setStyleSheet(u"")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Seven = QPushButton(self.frame)
        self.Seven.setObjectName(u"Seven")
        self.Seven.setGeometry(QRect(50, 290, 70, 60))
        self.Seven.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Four = QPushButton(self.frame)
        self.Four.setObjectName(u"Four")
        self.Four.setGeometry(QRect(50, 350, 70, 60))
        self.Four.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.One = QPushButton(self.frame)
        self.One.setObjectName(u"One")
        self.One.setGeometry(QRect(50, 410, 70, 60))
        self.One.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Eight = QPushButton(self.frame)
        self.Eight.setObjectName(u"Eight")
        self.Eight.setGeometry(QRect(120, 290, 70, 60))
        self.Eight.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Five = QPushButton(self.frame)
        self.Five.setObjectName(u"Five")
        self.Five.setGeometry(QRect(120, 350, 70, 60))
        self.Five.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Two = QPushButton(self.frame)
        self.Two.setObjectName(u"Two")
        self.Two.setGeometry(QRect(120, 410, 70, 60))
        self.Two.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Three = QPushButton(self.frame)
        self.Three.setObjectName(u"Three")
        self.Three.setGeometry(QRect(190, 410, 70, 60))
        self.Three.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Six = QPushButton(self.frame)
        self.Six.setObjectName(u"Six")
        self.Six.setGeometry(QRect(190, 350, 70, 60))
        self.Six.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Nine = QPushButton(self.frame)
        self.Nine.setObjectName(u"Nine")
        self.Nine.setGeometry(QRect(190, 290, 70, 60))
        self.Nine.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Multiply = QPushButton(self.frame)
        self.Multiply.setObjectName(u"Multiply")
        self.Multiply.setGeometry(QRect(260, 290, 70, 60))
        self.Multiply.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Substract = QPushButton(self.frame)
        self.Substract.setObjectName(u"Substract")
        self.Substract.setGeometry(QRect(260, 350, 70, 60))
        self.Substract.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Sum = QPushButton(self.frame)
        self.Sum.setObjectName(u"Sum")
        self.Sum.setGeometry(QRect(260, 410, 70, 61))
        self.Sum.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Exp = QPushButton(self.frame)
        self.Exp.setObjectName(u"Exp")
        self.Exp.setGeometry(QRect(50, 230, 70, 60))
        self.Exp.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Sqrt = QPushButton(self.frame)
        self.Sqrt.setObjectName(u"Sqrt")
        self.Sqrt.setGeometry(QRect(120, 230, 70, 60))
        self.Sqrt.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Percent = QPushButton(self.frame)
        self.Percent.setObjectName(u"Percent")
        self.Percent.setGeometry(QRect(190, 230, 70, 60))
        self.Percent.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Divide = QPushButton(self.frame)
        self.Divide.setObjectName(u"Divide")
        self.Divide.setGeometry(QRect(260, 230, 70, 60))
        self.Divide.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Cero = QPushButton(self.frame)
        self.Cero.setObjectName(u"Cero")
        self.Cero.setGeometry(QRect(50, 470, 70, 60))
        self.Cero.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Equal = QPushButton(self.frame)
        self.Equal.setObjectName(u"Equal")
        self.Equal.setGeometry(QRect(190, 470, 140, 60))
        self.Equal.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Result = QLabel(self.frame)
        self.Result.setObjectName(u"Result")
        self.Result.setGeometry(QRect(52, 40, 276, 61))
        font = QFont()
        font.setFamilies([u"Calculator"])
        font.setPointSize(26)
        self.Result.setFont(font)
        self.Result.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5%")
        self.Result.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.Result.setMargin(5)
        self.Clear = QPushButton(self.frame)
        self.Clear.setObjectName(u"Clear")
        self.Clear.setGeometry(QRect(50, 110, 70, 60))
        self.Clear.setStyleSheet(u"font: 16pt \"Calculator\";\n"
"background-color: rgb(255, 101, 101);")
        self.P_left = QPushButton(self.frame)
        self.P_left.setObjectName(u"P_left")
        self.P_left.setGeometry(QRect(120, 110, 70, 60))
        self.P_left.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.P_right = QPushButton(self.frame)
        self.P_right.setObjectName(u"P_right")
        self.P_right.setGeometry(QRect(190, 110, 70, 60))
        self.P_right.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Delete = QPushButton(self.frame)
        self.Delete.setObjectName(u"Delete")
        self.Delete.setGeometry(QRect(260, 110, 70, 60))
        self.Delete.setStyleSheet(u"font: 14pt \"Calculator\";")
        self.Coma = QPushButton(self.frame)
        self.Coma.setObjectName(u"Coma")
        self.Coma.setGeometry(QRect(120, 470, 70, 60))
        self.Coma.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.History = QTableWidget(self.frame)
        self.History.setObjectName(u"History")
        self.History.setGeometry(QRect(370, 40, 201, 371))
        self.History.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.History.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.History.setTabKeyNavigation(True)
        self.History.setShowGrid(True)
        self.History.setSortingEnabled(False)
        self.History.setColumnCount(0)
        self.Pi = QPushButton(self.frame)
        self.Pi.setObjectName(u"Pi")
        self.Pi.setGeometry(QRect(260, 170, 70, 60))
        self.Pi.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Factorial = QPushButton(self.frame)
        self.Factorial.setObjectName(u"Factorial")
        self.Factorial.setGeometry(QRect(190, 170, 70, 60))
        self.Factorial.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Log = QPushButton(self.frame)
        self.Log.setObjectName(u"Log")
        self.Log.setGeometry(QRect(50, 170, 70, 60))
        self.Log.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.Ln = QPushButton(self.frame)
        self.Ln.setObjectName(u"Ln")
        self.Ln.setGeometry(QRect(120, 170, 70, 60))
        self.Ln.setStyleSheet(u"font: 16pt \"Calculator\";")
        self.ClearH = QPushButton(self.frame)
        self.ClearH.setObjectName(u"ClearH")
        self.ClearH.setGeometry(QRect(400, 470, 141, 60))
        self.ClearH.setStyleSheet(u"font: 16pt \"Calculator\";\n"
"background-color: rgb(255, 101, 101);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 723, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Seven.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.Four.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.One.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.Eight.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.Five.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.Two.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.Three.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.Six.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.Nine.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.Multiply.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.Substract.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.Sum.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.Exp.setText(QCoreApplication.translate("MainWindow", u"^", None))
        self.Sqrt.setText(QCoreApplication.translate("MainWindow", u"\u221ax", None))
        self.Percent.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.Divide.setText(QCoreApplication.translate("MainWindow", u"\u00f7", None))
        self.Cero.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.Equal.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.Result.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.Clear.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.P_left.setText(QCoreApplication.translate("MainWindow", u"(", None))
        self.P_right.setText(QCoreApplication.translate("MainWindow", u")", None))
        self.Delete.setText(QCoreApplication.translate("MainWindow", u"\u232b", None))
        self.Coma.setText(QCoreApplication.translate("MainWindow", u",", None))
        self.Pi.setText(QCoreApplication.translate("MainWindow", u"\u03c0", None))
        self.Factorial.setText(QCoreApplication.translate("MainWindow", u"!", None))
        self.Log.setText(QCoreApplication.translate("MainWindow", u"log", None))
        self.Ln.setText(QCoreApplication.translate("MainWindow", u"ln", None))
        self.ClearH.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
    # retranslateUi

